{
 "title": "HDFC AMC - User Reports",
 "description": "User Reports - Extended Log Analysis provides in-depth insights into user activity logs, helping track access patterns, anomalies, and system interactions. With detailed filtering and visualization, it enhances security monitoring, compliance auditing, and performance analysis. Ideal for administrators and security teams",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "User",
    "query": "{\"find\": \"terms\", \"field\": \"username.keyword\"}"
   },
   {
    "name": "req_host",
    "label": "Destination",
    "query": "{\"find\": \"terms\", \"field\": \"request_host.keyword\"}"
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "{\"find\": \"terms\", \"field\": \"hostname.keyword\"}"
   },
   {
    "name": "server_ip",
    "label": "Server IP",
    "query": "{\"find\": \"terms\", \"field\": \"server_ip.keyword\", \"query\": \"hostname.keyword:$hostname\"}"
   }
  ]
 },
 "panels": [
  { "title": "General Usage Reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top User",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "username.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode: (\"TCP_DENIED\" OR \"TCP_SSL_HANDSHAKE\") AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top User Groups",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 7, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_groups.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode \"TCP_SSL_HANDSHAKE\" AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Site",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_host.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode: (\"TCP_DENIED\" OR \"TCP_SSL_HANDSHAKE\") AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application List",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "application_signatures.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode \"TCP_SSL_HANDSHAKE\" AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Endpoint Applications",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "useragent.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode \"TCP_SSL_HANDSHAKE\" AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "User Access",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "client_ip.keyword",
       "id": "14",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_key", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "username.keyword",
       "id": "15",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_key", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "request_host.keyword",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_key", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "method: ( \"CONNECT\" OR \"GET\" OR \"POST\" ) AND NOT cachecode: (\"TCP_DENIED\" OR \"TCP_SSL_HANDSHAKE\" ) AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "User Total Usage Time ",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "username.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      },
      {
       "field": "request_host.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode: \"TCP_SSL_HANDSHAKE\" AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Downloads",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_host.keyword",
       "id": "12",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "field": "download_content_types.keyword",
       "id": "14",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "13", "type": "count" }
     ],
     "query": "method: \"GET\" AND NOT cachecode: (\"TCP_DENIED\" OR  \"TCP_SSL_HANDSHAKE\" ) AND NOT download_content_types: \"-\" AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Uploads",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "upload_content_types.keyword",
       "id": "14",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      },
      {
       "field": "request_host.keyword",
       "id": "15",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "method: \"POST\" AND NOT cachecode: (\"TCP_DENIED\" OR  \"TCP_SSL_HANDSHAKE\" ) AND NOT upload_content_types: \"-\" AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "3",
       "type": "count"
      },
      { "id": "4", "type": "count" }
     ],
     "query": "AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Categories",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "categories.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode \"TCP_SSL_HANDSHAKE\" AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hits of users",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "username.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode:(\"TCP_DENIED\" OR \"TCP_SSL_HANDSHAKE\" ) AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Traffic by User",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "username.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "NOT cachecode: (\"TCP_DENIED\" OR \"TCP_SSL_HANDSHAKE\" )  AND method: ( \"CONNECT\" OR \"GET\" OR \"POST\") AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Destinations",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_host.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT cachecode: ( \"TCP_DENIED\" OR \"TCP_SSL_HANDSHAKE\" ) AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Blocked Destinations ",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_host.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "field": "username.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": "1",
        "missing": "anonyms",
        "order": "desc",
        "orderBy": "_key",
        "size": "20"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "status: 451 AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Geo Destination",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "field": "peer.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT peer.keyword: \"\\\"-\\\"\" AND (method:CONNECT OR method:GET OR method:POST) AND NOT cachdecode:\"TCP_DENIED\" AND requested_host:$req_host AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TCP Status Code",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cachecode.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Host and its Referers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "request_host.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      },
      {
       "field": "http_referer.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT http_referer: \"-\" AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "User Threat Reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Top Blocked Categories",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "categories.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "status: ( 451 or 453 ) AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Threat Prevented By",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "categories.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      },
      {
       "field": "filter_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "10" },
       "type": "terms"
      },
      {
       "field": "filtering_reason.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "categories:( \"Anonymizers\" OR \n           \"Botnets\" OR \n           \"Compromised\" OR \n           \"Hacking\" OR \n           \"Illegal Software\" OR \n           \"Malware\" OR \n           \"Peer-to-Peer\" OR \n           \"Phishing & Fraud\" OR \n           \"Spam Sites\" OR \n           \"Alcohol & Tobacco\" OR \n           \"Criminal Activity\" OR \n           \"Cults\" OR \n           \"Gambling\" OR \n           \"Hate & Intolerance\" OR \n           \"Illegal Drug\" OR \n           \"School Cheating\" OR \n           \"Tasteless\" OR \n           \"Unknown\" OR \n           \"Violence\" ) AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Malware Downloads",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "username.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      },
      {
       "field": "filtering_reason.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      },
      {
       "field": "filter_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      },
      {
       "field": "request_host.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: (451 OR 453) AND method: \"GET\" AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Malware Uploads",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_groups.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      },
      {
       "field": "filtering_reason.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      },
      {
       "field": "filter_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      },
      {
       "field": "request_host.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: (451 OR 453) AND method: \"POST\" AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Threatful Categories and Host",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "categories.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      },
      {
       "field": "request_host.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "categories:( \"Anonymizers\" OR \n           \"Botnets\" OR \n           \"Compromised\" OR \n           \"Hacking\" OR \n           \"Illegal Software\" OR \n           \"Malware\" OR \n           \"Peer-to-Peer\" OR \n           \"Phishing & Fraud\" OR \n           \"Spam Sites\" OR \n           \"Alcohol & Tobacco\" OR \n           \"Criminal Activity\" OR \n           \"Cults\" OR \n           \"Gambling\" OR \n           \"Hate & Intolerance\" OR \n           \"Illegal Drug\" OR \n           \"School Cheating\" OR \n           \"Tasteless\" OR \n           \"Unknown\" OR  \n           \"Violence\" ) AND NOT cachecode: \"TCP_SSL_HANDSHAKE\" AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hosts with SSL Inspection Bypassed",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "request_host.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "cachecode: \"TCP_TUNNEL\" AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Threatful User",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "categories.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      },
      {
       "field": "username.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "20" },
       "type": "terms"
      },
      {
       "field": "client_ip.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_key", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "categories:( \"Anonymizers\" OR \n           \"Botnets\" OR \n           \"Compromised\" OR \n           \"Hacking\" OR \n           \"Illegal Software\" OR \n           \"Malware\" OR \n           \"Peer-to-Peer\" OR \n           \"Phishing & Fraud\" OR \n           \"Spam Sites\" OR \n           \"Alcohol & Tobacco\" OR \n           \"Criminal Activity\" OR \n           \"Cults\" OR \n           \"Gambling\" OR \n           \"Hate & Intolerance\" OR \n           \"Illegal Drug\" OR \n           \"School Cheating\" OR \n           \"Tasteless\" OR \n           \"Unknown\" OR \n           \"Violence\" ) AND NOT cachecode: \"TCP_SSL_HANDSHAKE\" AND NOT username.keyword: \"https\" AND hostname.keyword:$hostname AND server_ip.keyword:$server_ip",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}